# Generated by Django 6.0.7 on 2026-09-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('phd', 'Doctor of Philosophy (PhD)'), ('edd', 'Doctor of Education (EdD)'), ('mphil', 'Master of Philosophy (MPhil)'), ('mrm', 'Master in Research Methodology (MRM)')], max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator_notes', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('previous_surname', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('home_province', models.CharField(blank=True, max_length=100)),
                ('residence_during_study', models.CharField(blank=True, max_length=150)),
                ('previously_enrolled', models.CharField(blank=True, max_length=5)),
                ('previous_student_id', models.CharField(blank=True, max_length=50)),
                ('disabilities', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('mobile_phone', models.CharField(blank=True, max_length=30)),
                ('work_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_name', models.CharField(blank=True, max_length=150)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_mobile', models.CharField(blank=True, max_length=30)),
                ('emergency_email', models.EmailField(blank=True, max_length=254)),
                ('award', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year_started', models.PositiveIntegerField(blank=True, null=True)),
                ('year_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('other_qualifications', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('study_mode', models.CharField(blank=True, max_length=30)),
                ('fee_payment_method', models.CharField(blank=True, max_length=50)),
                ('research_topic', models.CharField(blank=True, max_length=255)),
                ('research_outline', models.TextField(blank=True)),
                ('statement_of_purpose', models.TextField(blank=True)),
                ('previous_work', models.TextField(blank=True)),
                ('equipment_travel', models.TextField(blank=True)),
                ('supervisor_arrangement', models.TextField(blank=True)),
                ('declaration', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fee_receipt', 'Application Fee Receipt'), ('qualification', 'Qualification Documents'), ('cv', 'Curriculum Vitae'), ('reference', 'Professional Reference')], max_length=20)),
                ('file', models.FileField(upload_to='applications/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research.application')),
            ],
        ),
    ]
